version: "3.8"

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: caching-demo
      POSTGRES_USER: demo_user
      POSTGRES_PASSWORD: demo_pass
    ports:
      - 5432:5432
  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - /data
  redis-commander:
    image: rediscommander/redis-commander:latest
    build: .
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8082:8081"
