spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/caching-demo
    username: demo_user
    password: demo_pass
    hikari:
      data-source-properties:
        stringtype: unspecified
  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate.ddl-auto: update
